/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as OrdersReferenceRouteImport } from './routes/orders.$reference'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as ApiInternalPaymentMaintenanceRouteImport } from './routes/api/internal/payment-maintenance'
import { Route as AuthenticatedAdminOrdersIndexRouteImport } from './routes/_authenticated/admin.orders.index'
import { Route as AuthenticatedAdminOrdersReferenceRouteImport } from './routes/_authenticated/admin.orders.$reference'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin.products.index'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin.products.$id'
import { Route as ApiPublicDownloadTokenRouteImport } from './routes/api/public/download.$token'
import { Route as ApiPublicProductImageSplatRouteImport } from './routes/api/public/product-image.$'
import { Route as ApiPublicWebhooksFlutterwaveRouteImport } from './routes/api/public/webhooks/flutterwave'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrdersReferenceRoute = OrdersReferenceRouteImport.update({
  id: '/orders/$reference',
  path: '/orders/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiInternalPaymentMaintenanceRoute =
  ApiInternalPaymentMaintenanceRouteImport.update({
    id: '/api/internal/payment-maintenance',
    path: '/api/internal/payment-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminOrdersIndexRoute =
  AuthenticatedAdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersReferenceRoute =
  AuthenticatedAdminOrdersReferenceRouteImport.update({
    id: '/orders/$reference',
    path: '/orders/$reference',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/products/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicDownloadTokenRoute = ApiPublicDownloadTokenRouteImport.update({
  id: '/api/public/download/$token',
  path: '/api/public/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductImageSplatRoute =
  ApiPublicProductImageSplatRouteImport.update({
    id: '/api/public/product-image/$',
    path: '/api/public/product-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksFlutterwaveRoute =
  ApiPublicWebhooksFlutterwaveRouteImport.update({
    id: '/api/public/webhooks/flutterwave',
    path: '/api/public/webhooks/flutterwave',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/orders/$reference': typeof OrdersReferenceRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/internal/payment-maintenance': typeof ApiInternalPaymentMaintenanceRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$reference': typeof AuthenticatedAdminOrdersReferenceRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/download/$token': typeof ApiPublicDownloadTokenRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/api/public/webhooks/flutterwave': typeof ApiPublicWebhooksFlutterwaveRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/orders/$reference': typeof OrdersReferenceRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/internal/payment-maintenance': typeof ApiInternalPaymentMaintenanceRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$reference': typeof AuthenticatedAdminOrdersReferenceRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/download/$token': typeof ApiPublicDownloadTokenRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/api/public/webhooks/flutterwave': typeof ApiPublicWebhooksFlutterwaveRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/orders/$reference': typeof OrdersReferenceRoute
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/internal/payment-maintenance': typeof ApiInternalPaymentMaintenanceRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/orders/$reference': typeof AuthenticatedAdminOrdersReferenceRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/download/$token': typeof ApiPublicDownloadTokenRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/api/public/webhooks/flutterwave': typeof ApiPublicWebhooksFlutterwaveRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/_authenticated/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/auth'
    | '/setup'
    | '/admin'
    | '/orders/$reference'
    | '/p/$slug'
    | '/admin/customers'
    | '/admin/settings'
    | '/api/internal/payment-maintenance'
    | '/admin/'
    | '/admin/orders/$reference'
    | '/admin/products/$id'
    | '/api/public/download/$token'
    | '/api/public/product-image/$'
    | '/api/public/webhooks/flutterwave'
    | '/api/public/webhooks/paystack'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/auth'
    | '/setup'
    | '/orders/$reference'
    | '/p/$slug'
    | '/admin/customers'
    | '/admin/settings'
    | '/api/internal/payment-maintenance'
    | '/admin'
    | '/admin/orders/$reference'
    | '/admin/products/$id'
    | '/api/public/download/$token'
    | '/api/public/product-image/$'
    | '/api/public/webhooks/flutterwave'
    | '/api/public/webhooks/paystack'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activate'
    | '/auth'
    | '/setup'
    | '/_authenticated/admin'
    | '/orders/$reference'
    | '/p/$slug'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/settings'
    | '/api/internal/payment-maintenance'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/orders/$reference'
    | '/_authenticated/admin/products/$id'
    | '/api/public/download/$token'
    | '/api/public/product-image/$'
    | '/api/public/webhooks/flutterwave'
    | '/api/public/webhooks/paystack'
    | '/_authenticated/admin/orders/'
    | '/_authenticated/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
  OrdersReferenceRoute: typeof OrdersReferenceRoute
  PSlugRoute: typeof PSlugRoute
  ApiInternalPaymentMaintenanceRoute: typeof ApiInternalPaymentMaintenanceRoute
  ApiPublicDownloadTokenRoute: typeof ApiPublicDownloadTokenRoute
  ApiPublicProductImageSplatRoute: typeof ApiPublicProductImageSplatRoute
  ApiPublicWebhooksFlutterwaveRoute: typeof ApiPublicWebhooksFlutterwaveRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/orders/$reference': {
      id: '/orders/$reference'
      path: '/orders/$reference'
      fullPath: '/orders/$reference'
      preLoaderRoute: typeof OrdersReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/internal/payment-maintenance': {
      id: '/api/internal/payment-maintenance'
      path: '/api/internal/payment-maintenance'
      fullPath: '/api/internal/payment-maintenance'
      preLoaderRoute: typeof ApiInternalPaymentMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/orders/': {
      id: '/_authenticated/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/$reference': {
      id: '/_authenticated/admin/orders/$reference'
      path: '/orders/$reference'
      fullPath: '/admin/orders/$reference'
      preLoaderRoute: typeof AuthenticatedAdminOrdersReferenceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/download/$token': {
      id: '/api/public/download/$token'
      path: '/api/public/download/$token'
      fullPath: '/api/public/download/$token'
      preLoaderRoute: typeof ApiPublicDownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-image/$': {
      id: '/api/public/product-image/$'
      path: '/api/public/product-image/$'
      fullPath: '/api/public/product-image/$'
      preLoaderRoute: typeof ApiPublicProductImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/flutterwave': {
      id: '/api/public/webhooks/flutterwave'
      path: '/api/public/webhooks/flutterwave'
      fullPath: '/api/public/webhooks/flutterwave'
      preLoaderRoute: typeof ApiPublicWebhooksFlutterwaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOrdersReferenceRoute: typeof AuthenticatedAdminOrdersReferenceRoute
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminOrdersIndexRoute: typeof AuthenticatedAdminOrdersIndexRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminOrdersReferenceRoute:
    AuthenticatedAdminOrdersReferenceRoute,
  AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
  AuthenticatedAdminOrdersIndexRoute: AuthenticatedAdminOrdersIndexRoute,
  AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivateRoute: ActivateRoute,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
  OrdersReferenceRoute: OrdersReferenceRoute,
  PSlugRoute: PSlugRoute,
  ApiInternalPaymentMaintenanceRoute: ApiInternalPaymentMaintenanceRoute,
  ApiPublicDownloadTokenRoute: ApiPublicDownloadTokenRoute,
  ApiPublicProductImageSplatRoute: ApiPublicProductImageSplatRoute,
  ApiPublicWebhooksFlutterwaveRoute: ApiPublicWebhooksFlutterwaveRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
